# Generated by Django 4.1.3 on 2023-02-13 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='profile_pics/')),
                ('school', models.CharField(max_length=200, null=True)),
                ('notification_type', models.IntegerField(choices=[(1, 'Save'), (2, 'Unsave')], null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profession', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='files/pdfs/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('save_pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_pdf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
