# Generated by Django 4.1.3 on 2023-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'dbuser',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterModelTable(
            name='file',
            table='dbfile',
        ),
    ]
