# Generated by Django 4.1.3 on 2023-01-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0002_userdb_delete_customer_alter_file_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdb',
        ),
        migrations.AlterModelTable(
            name='file',
            table=None,
        ),
    ]
