# Generated by Django 4.1.3 on 2022-11-29 18:18

import django.contrib.auth.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("virtual", "0002_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("virtual.user",),
            managers=[
                ("lecturer", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
