# Generated by Django 4.1.4 on 2023-01-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0003_rename_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='school',
        ),
    ]
