# Generated by Django 4.1.4 on 2023-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0005_rename_bio_profile_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='files/pdfs/'),
        ),
    ]
