# Generated by Django 4.1.4 on 2023-02-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0008_notify_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='time',
            field=models.TimeField(blank=True, verbose_name='Time'),
        ),
    ]
