# Generated by Django 4.1.4 on 2023-02-13 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual', '0009_alter_notify_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='time',
        ),
        migrations.AddField(
            model_name='notify',
            name='save_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_pdf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Save'), (2, 'Unsave')], null=True),
        ),
    ]
