# Generated by Django 4.1.4 on 2023-02-13 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('virtual', '0010_remove_notify_file_name_remove_notify_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='save_pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save_pdf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notify',
        ),
    ]
